# Generated by Django 2.2.6 on 2022-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200311_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(max_length=200, upload_to='course/resouces/%Y/%m/', verbose_name='视频地址'),
        ),
    ]
